### ISSUE TITLE
Multiple JS projects when using cross build?

### ISSUE THREAD

**Issue by Voltir** [vmunier/sbt-play-scalajs#1]
I think I might want to serve multiple different js applications from the same play backend, but it is not clear how to setup the build file when using the cross build plugin.

**Comment by vmunier** [comment]
Hi @Voltir 
It's true that using the Scala.js CrossProject type does not allow to define multiple js projects for one jvm project. Maybe that's something `CrossProject` should support. I would recommend you to ask your question again on the mailing list or open an issue on the scala-js repo.

Right now, I find it pretty convenient to reuse CrossProject from the Scala.js sbt-plugin because you've got access to its util methods for free http://www.scala-js.org/api/sbt-scalajs/0.6.0-RC1/#org.scalajs.sbtplugin.cross.CrossProject. But if it's a real need to support js projects we might need to move away from CrossProject in this `sbt-play-scalajs` plugin.

**Comment by Voltir** [comment]
So I used the migrate to 0.6.0-M2 branch project file as my starting point, instead of the more recent one as my template, so adding multiple js projects was a non-issue. I personally probably wont use the sbt-play-scalajs plugin as is because it just seems weird limiting a play application to only have one js project, when I want to do things like have a frontends for mobile, web and admin all using the same play backend.

**Comment by vmunier** [comment]
For the time being, you should indeed follow the 0.6.0-M2 branch if you want to add multiple js projects. I need a thorough rethink of this sbt-play-scalajs to support multiple js projects. I also plan to only use CrossProject for a shared project as it was meant to be used.

**Comment by vmunier** [comment]
Hi @Voltir,

I am coming back to you because I have published a new version of sbt-play-scalajs v0.2.0. It's a complete rewrite of the plugin. 

You can now attach several Scala.js projects to the Play! project using the `scalaJSProjects` setting.
The README.md shows how to set it up but I will also update play-with-scalajs-example soon to make things clear.

Please let me know if you have any questions/suggestions on this new rewrite of the plugin.

**Comment by vmunier** [comment]
[play-with-scalajs-example](https://github.com/vmunier/play-with-scalajs-example) has also been updated. Use the `scalaJSProjects` setting to attach several Scala.js projects to the Play! project.

**Comment by Voltir** [comment]
So, I was able to get our largest internal project to use this plugin. I ran into a couple of issues though:

First, I have some issues with intellij + the new project layout. Intellij is picking up the .jvm / .js files from the crossProject, but not any of the source code in my shared directory. This leads to all manner of red squigglies wherever shared source code is used. My setup is "old" -- I am staying on 13.1 and using the sbt plugin that provides gen-idea while the issues with intellij 14 get sorted out. 

The second problem is a bit more disconcerting. Using my previous build script, making changes to my scala.js code took about 10-15 seconds to recompile -- with the new plugin however, the build seems to take 45+ seconds, even with just trivial changes. It also appears to execute fastOptJS twice per scalajs project. I upgraded my old build script to pull down all the latest versions of scala.js and various libs, so I now have basically two equivalent build files: one using this plugin, and one that follows the older style -- so I am pretty sure I ruled out anything to do with just project updates.

**Comment by vmunier** [comment]
Hi @Voltir, 
For IntelliJ integration, try using the latest version of the IntelliJ Scala Plugin, v1.3.3.
I added a section in [play-with-scalajs-example](https://github.com/vmunier/play-with-scalajs-example#user-content-intellij) recently and it seems to work fine with this version.

For the longer time it takes to compile, I don't know what is the cause... There should be a way to avoid fastOptJS to be called twice per Scala.js project. But even if fastOptJS is called twice, the second call should be really quick because of incremental compilation.

**Comment by vmunier** [comment]
@Voltir, if you upgrade to `sbt-play-scalajs` v0.2.2, fastOptJS will be called once per Scala.js project.
I don't think it will really improve the performance because Scala.js uses incremental compilation but it can't be worse at least :)

**Comment by Voltir** [comment]
Thanks for the update -- I still haven't done much testing yet on the larger project. We are currently evaluating if intellij 14 + scala plugin 1.3.3 will work for us... I am a bit hesitant to step away from gen-idea with all the pain I suffered through trying to make intellij's import work originally.

**Comment by decapo01** [comment]
I'm trying to make multiple scalajs apps in my project but am not clear how to do so with the scalaJSProjects setting.  Can you update the play-with-scalajs-example to show how to use this with multiple scala js projects?

**Comment by decapo01** [comment]
I see it now.  I was looking in the client build for the scalaJSProjects setting but on second (actually forth or fifth) glance I see the scalaJSProjects setting in the server build definition.  I'm not sure if this should be a new issue or not but is there a way to have multiple main methods in one scalajs project and specify which one goes on a page in the twirl template?
