### ISSUE TITLE
How to enable SbtWeb & pipelines

### ISSUE THREAD

**Issue by lespea** [vmunier/sbt-play-scalajs#2]
I'm not sure how you enable plugins on the play submodule so I can enable SbtWeb and turn on some pipelines (digest, gzip, etc).  I've tried adding it onto both the PlayScalaJS project and the one referenced from playScalaJs.jvm.  Is this something that just isn't possible or am I just doing something really stupid?

**Comment by sjrd** [comment]
```Scala
.jvmConfigure(_.enablePlugins(...))
```
on the `CrossProject` should do it.

**Comment by vmunier** [comment]
Hi @lespea,

A Play app already depends on SbtWeb, so you don't need to enable the SbtWeb plugin.
Say you want to include the [sbt-gzip](https://github.com/sbt/sbt-gzip) plugin:
* in `project/plugins.sbt` add `addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.0")`
* In `project/Build.scala` you need to add two imports and set the pipelineStages setting key:
```
import com.typesafe.sbt.web.SbtWeb.autoImport._
import com.typesafe.sbt.gzip.SbtGzip.autoImport._

...
lazy val playScalaJS: CrossProject = PlayScalaJS("example", file(".")).
  jvmSettings(pipelineStages := Seq(gzip))
...
```

Unfortunately the js files output by the Scala.js compilation won't be gzipped because sbt-play-scalajs does not follow the conventions of sbt-web.
I don't know sbt-web well enough, so that's something I should explore and see wether it's possible to make sbt-play-scalajs compliant with sbt-web.

**Comment by lespea** [comment]
Oh turns out it wasn't working before because I was adding the assembly plugin for another subproject I was using.  Thanks for the replies everybody :)
