### ISSUE TITLE
Pass parameters

### ISSUE THREAD

**Issue by joan38** [vmunier/sbt-play-scalajs#6]
Hi,

First this plugin is just what was missing to the Scala-JS/Play projects, thanks.

I see that we can include the JS by calling [playscalajs.html.scripts](https://github.com/vmunier/play-with-scalajs-example/blob/303bfdcf3121d0d45e9425945f7480f84a81ccac/example-server/app/views/main.scala.html#L16).
I assume then that the main gets called automatically?
But I'm wondering if we can pass a parameter to this main? Or if we can call another function? With parameters?

Cheers

**Comment by vmunier** [comment]
Hi @joan38,

FYI `playscalajs.html.scripts` comes from this library https://github.com/vmunier/play-scalajs-scripts.
The main gets called automatically because the Scala.js launcher is included: [scripts.scala.html](https://github.com/vmunier/play-scalajs-scripts/blob/master/app/playscalajs/scripts.scala.html) calls [launcher.scala.html](https://github.com/vmunier/play-scalajs-scripts/blob/master/app/playscalajs/launcher.scala.html).

If you want to call the `main` method with specific parameters or call another function, I suggest using [selectScript.scala.html](https://github.com/vmunier/play-scalajs-scripts/blob/master/app/playscalajs/selectScript.scala.html) only, e.g: `@playscalajs.html.selectScript("/assets", projectName = "exampleClient")`.

You will also need to export your main method:
```
import js.annotation.JSExport

@JSExport
object ScalaJSExample extends js.JSApp {
  @JSExport
  def main(): Unit = {
  }
}
```

Then you can call your method explicitly and pass arguments:
```
<script type="text/javascript">
ScalaJSExample().main();
</script>
```

**Comment by joan38** [comment]
Thank you very much for this information, very helpful.
