### ISSUE TITLE
Trigger recompile on js project change

### ISSUE THREAD

**Issue by giovannicandido** [vmunier/sbt-play-scalajs#9]
Hi,
How to trigger a recompile and copy of resources when the jsclient project is updated?

The follow use case:

1. Change code in scala js
2. Reload the play page and incrementally recompile, see the code changed.

Now I do the follow

1. Change scalala js code
2. Make a empty change in server template (like a empty space)
3. Play trigger the recompile on server and this cascade to jsclient
4. Change is recompiled and appear on the page

Today changes in scalajs do not appear in the result of server automatically.
The server recompile is not needed, as it is a resource.

Using version 0.2.4 and play 2.4.0-RC1

**Comment by vmunier** [comment]
Hi,
I confirm that Scala.js compilation is not triggered after upgrading to play 2.4.0-RC1.
Please let me know if you've got a fix. I'll probably wait until this weekend to look at it.
Thanks for reporting the issue.

**Comment by zlangbert** [comment]
Hitting the same issue, any updates on this?

**Comment by vmunier** [comment]
Changes to the example-shared files are detected because they are part of the server's classpath when dependsOn is used https://github.com/vmunier/play-with-scalajs-example/blob/master/build.sbt#L19.

But the source files from the Scala.js project (that is example-client in https://github.com/vmunier/play-with-scalajs-example) are not watched anymore when using Play 2.4.
I spent a bit of time looking into it but I haven't found a solution yet, it's not a quick fix.

**Comment by vmunier** [comment]
Hi @giovannicandido, @zlangbert,
sbt-play-scalajs v0.2.6 has been published to be used along with Play 2.4.
Note that it remains compatible with Play 2.3.x.

Play 2.4 has stopped monitoring some directories that it used to watch on Play run.
The Scala.js projects are now added to `unmanagedSourceDirectories in Assets` to be part of the directories monitored by Play.
